"""WAF detection, technology fingerprinting, and security header analysis.
Ultra v3.0.0 — 80+ WAF signatures, CVE detection, OWASP scoring.
"""

from __future__ import annotations

import logging
import re
from typing import Any, Dict, List, Optional, Tuple

from http_auditor_ultra.client import AuditResult

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# WAF signatures — 80+ entries
# ---------------------------------------------------------------------------

WAF_SIGNATURES: List[Tuple[str, str, str, str]] = [
    # Cloudflare
    ("Cloudflare", "header", "server", r"cloudflare"),
    ("Cloudflare", "header", "cf-ray", r".+"),
    ("Cloudflare", "header", "cf-cache-status", r".+"),
    ("Cloudflare", "header", "cf-request-id", r".+"),
    ("Cloudflare", "cookie", "cf_clearance", r".+"),
    ("Cloudflare", "body", "__cf_chl_f_tk", r".+"),
    ("Cloudflare", "body", "cloudflare ray id", r".+"),
    ("Cloudflare", "body", "attention required! cloudflare", r".+"),
    # AWS WAF / CloudFront
    ("AWS CloudFront", "header", "x-amz-cf-id", r".+"),
    ("AWS CloudFront", "header", "x-amz-cf-pop", r".+"),
    ("AWS WAF", "header", "x-amzn-requestid", r".+"),
    ("AWS WAF", "header", "x-amzn-errortype", r".+"),
    ("AWS WAF", "header", "x-amzn-trace-id", r".+"),
    ("AWS WAF", "body", "request blocked by aws waf", r".+"),
    # ModSecurity
    ("ModSecurity", "header", "x-powered-by", r"(?i)ModSecurity"),
    ("ModSecurity", "body", "modsecurity", r".+"),
    ("ModSecurity", "body", "not acceptable", r".+"),
    # Akamai
    ("Akamai Ghost", "header", "server", r"(?i)AkamaiGHost"),
    ("Akamai", "header", "x-akamai-request-id", r".+"),
    ("Akamai", "header", "x-akamai-transformed", r".+"),
    ("Akamai", "header", "x-check-cacheable", r".+"),
    ("Akamai", "body", "reference #", r".+"),
    # Imperva / Incapsula
    ("Imperva Incapsula", "header", "x-iinfo", r".+"),
    ("Imperva Incapsula", "header", "x-cdn", r"(?i)Incapsula"),
    ("Imperva Incapsula", "cookie", "incap_ses", r".+"),
    ("Imperva Incapsula", "cookie", "visid_incap", r".+"),
    ("Imperva Incapsula", "body", "incapsula incident id", r".+"),
    # F5 BIG-IP ASM
    ("F5 BIG-IP ASM", "header", "x-waf-result", r".+"),
    ("F5 BIG-IP ASM", "header", "x-cnection", r".+"),
    ("F5 BIG-IP ASM", "cookie", "TS", r"\w{20,}"),
    ("F5 BIG-IP ASM", "body", "the requested url was rejected", r".+"),
    ("F5 BIG-IP ASM", "body", "please consult with your administrator", r".+"),
    # Sucuri
    ("Sucuri", "header", "x-sucuri-id", r".+"),
    ("Sucuri", "header", "x-sucuri-cache", r".+"),
    ("Sucuri", "body", "cloudproxy@sucuri.net", r".+"),
    ("Sucuri", "body", "sucuri website firewall", r".+"),
    # Wordfence
    ("Wordfence", "body", "wordfence", r".+"),
    ("Wordfence", "body", "generated by wordfence", r".+"),
    # Barracuda
    ("Barracuda WAF", "cookie", "barra_counter_session", r".+"),
    ("Barracuda WAF", "body", "barracuda networks", r".+"),
    # Fortinet FortiWeb
    ("FortiWeb", "header", "x-waf-result", r"(?i)fortiwaf"),
    ("FortiWeb", "cookie", "FORTIWAFSID", r".+"),
    ("FortiWeb", "body", "fortiwaf", r".+"),
    # Radware AppWall
    ("Radware AppWall", "header", "x-sl-compstate", r".+"),
    ("Radware AppWall", "cookie", "rdwr", r".+"),
    ("Radware AppWall", "body", "unauthorized activity has been detected", r".+"),
    # Citrix NetScaler
    ("Citrix NetScaler", "cookie", "NSC_", r".+"),
    ("Citrix NetScaler", "header", "via", r"(?i)NS-CACHE"),
    ("Citrix NetScaler", "header", "x-nsreason", r".+"),
    # StackPath
    ("StackPath", "header", "x-sp-url", r".+"),
    ("StackPath", "header", "x-sp-waf", r".+"),
    # Alibaba Cloud WAF
    ("Alibaba Cloud WAF", "header", "ali-swift-global-savetime", r".+"),
    ("Alibaba Cloud WAF", "header", "eagleid", r".+"),
    ("Alibaba Cloud WAF", "body", "blocked by alibaba cloud shield", r".+"),
    # Tencent Cloud WAF
    ("Tencent Cloud WAF", "header", "x-client-ip", r".+"),
    ("Tencent Cloud WAF", "body", "tencent cloud waf", r".+"),
    # Huawei Cloud WAF
    ("Huawei Cloud WAF", "header", "x-hws-waf", r".+"),
    ("Huawei Cloud WAF", "body", "huawei cloud waf", r".+"),
    # Azure Front Door
    ("Azure Front Door", "header", "x-azure-ref", r".+"),
    ("Azure Front Door", "header", "x-fd-healthprobe", r".+"),
    # Google Cloud Armor
    ("Google Cloud Armor", "body", "your client does not have permission", r".+"),
    ("Google Cloud Armor", "header", "via", r"(?i)google"),
    # LiteSpeed
    ("LiteSpeed", "header", "server", r"(?i)LiteSpeed"),
    ("LiteSpeed", "header", "x-litespeed-cache", r".+"),
    # SafeLine
    ("SafeLine", "header", "server", r"(?i)SafeLine"),
    ("SafeLine", "header", "x-safeline-id", r".+"),
    # Nginx WAF (generic)
    ("Nginx WAF", "header", "x-nginx-cache", r".+"),
    # Comodo cWatch
    ("Comodo cWatch", "body", "access denied by cwatch", r".+"),
    # DenyAll
    ("DenyAll WAF", "cookie", "sessioncookie", r".+"),
    ("DenyAll WAF", "body", "denyall", r".+"),
    # Reblaze
    ("Reblaze", "header", "x-reblaze-protection", r".+"),
    ("Reblaze", "cookie", "rbzid", r".+"),
    # Wallarm
    ("Wallarm", "header", "x-wallarm-node", r".+"),
    # Fastly WAF (Signal Sciences)
    ("Fastly WAF", "header", "x-sigsci-tags", r".+"),
    ("Fastly WAF", "header", "x-sigsci-requestid", r".+"),
    # Varnish
    ("Varnish Cache", "header", "x-varnish", r".+"),
    ("Varnish Cache", "header", "via", r"(?i)varnish"),
    # Generic heuristics last
    ("Unknown WAF", "header", "x-waf-event-info", r".+"),
    ("Unknown WAF", "header", "x-waf-score", r".+"),
]

# ---------------------------------------------------------------------------
# Technology fingerprinting — 50+ signatures
# ---------------------------------------------------------------------------

TECH_SIGNATURES: List[Tuple[str, str, str]] = [
    # Web Servers
    ("Nginx", "header:server", r"(?i)nginx"),
    ("Apache", "header:server", r"(?i)Apache"),
    ("IIS", "header:server", r"(?i)Microsoft-IIS"),
    ("Tomcat", "header:server", r"(?i)Tomcat"),
    ("Jetty", "header:server", r"(?i)Jetty"),
    ("Caddy", "header:server", r"(?i)Caddy"),
    ("OpenResty", "header:server", r"(?i)openresty"),
    ("Gunicorn", "header:server", r"(?i)gunicorn"),
    ("Uvicorn", "header:server", r"(?i)uvicorn"),
    ("LiteSpeed", "header:server", r"(?i)LiteSpeed"),
    ("H2O", "header:server", r"(?i)h2o"),
    # Languages / Frameworks
    ("PHP", "header:x-powered-by", r"(?i)PHP"),
    ("ASP.NET", "header:x-powered-by", r"(?i)ASP\.NET"),
    ("Python/Django", "header:server", r"(?i)WSGIServer"),
    ("Python/Flask", "header:server", r"(?i)Werkzeug"),
    ("Python/aiohttp", "header:server", r"(?i)aiohttp"),
    ("Node.js/Express", "header:x-powered-by", r"(?i)Express"),
    ("Ruby on Rails", "header:x-powered-by", r"(?i)Phusion Passenger"),
    ("Java/Spring", "header:x-application-context", r".+"),
    ("Go", "header:server", r"(?i)Go-http-client"),
    ("Rust/Actix", "header:server", r"(?i)actix"),
    # CMS
    ("WordPress", "header:x-powered-by", r"(?i)WordPress"),
    ("WordPress", "body", r"wp-content"),
    ("WordPress", "body", r"wp-includes"),
    ("WordPress", "body", r"/wp-json/"),
    ("Drupal", "header:x-generator", r"(?i)Drupal"),
    ("Drupal", "header:x-drupal-cache", r".+"),
    ("Drupal", "body", r"(?i)drupal"),
    ("Joomla", "header:x-generator", r"(?i)Joomla"),
    ("Joomla", "body", r"(?i)joomla"),
    ("Magento", "body", r"(?i)Magento"),
    ("Magento", "header:x-magento-cache-debug", r".+"),
    ("Shopify", "header:x-shopid", r".+"),
    ("Shopify", "body", r"(?i)shopify"),
    ("Ghost CMS", "header:x-ghost-cache-status", r".+"),
    ("Ghost CMS", "body", r"(?i)ghost.org"),
    ("Wix", "header:x-wix-request-id", r".+"),
    ("Squarespace", "header:server", r"(?i)Squarespace"),
    # JS Frameworks
    ("React", "body", r"__REACT_DEVTOOLS"),
    ("Next.js", "header:x-powered-by", r"(?i)Next\.js"),
    ("Next.js", "body", r"__NEXT_DATA__"),
    ("Nuxt.js", "body", r"__NUXT__"),
    ("Angular", "body", r"ng-version"),
    ("Vue.js", "body", r"__vue_app__"),
    ("jQuery", "body", r"jquery"),
    # CDNs
    ("Cloudflare CDN", "header:cf-ray", r".+"),
    ("Akamai CDN", "header:x-akamai-request-id", r".+"),
    ("Fastly CDN", "header:x-fastly-request-id", r".+"),
    ("CloudFront CDN", "header:x-amz-cf-id", r".+"),
    ("KeyCDN", "header:x-cache", r"(?i)keycdn"),
    ("BunnyCDN", "header:cdn-requestid", r".+"),
    # Databases (via headers/errors)
    ("MySQL", "body", r"(?i)mysql_"),
    ("MongoDB", "body", r"(?i)mongodb"),
    ("Redis", "header:x-redis-cache", r".+"),
    # Security Products
    ("reCAPTCHA", "body", r"google.com/recaptcha"),
    ("hCaptcha", "body", r"hcaptcha.com"),
    ("Stripe", "body", r"js.stripe.com"),
    ("PayPal", "body", r"paypal.com/sdk"),
]

# ---------------------------------------------------------------------------
# Security headers — OWASP + extras
# ---------------------------------------------------------------------------

SECURITY_HEADERS_REQUIRED: Dict[str, Dict[str, Any]] = {
    "strict-transport-security": {
        "description": "HSTS — enforces HTTPS connections",
        "severity": "HIGH",
        "recommended_value": "max-age=31536000; includeSubDomains; preload",
        "cve_risk": "Man-in-the-middle attacks, SSL stripping",
    },
    "content-security-policy": {
        "description": "CSP — prevents XSS and data injection",
        "severity": "HIGH",
        "recommended_value": "default-src 'self'; script-src 'self'",
        "cve_risk": "XSS, clickjacking, data exfiltration",
    },
    "x-frame-options": {
        "description": "X-Frame-Options — prevents clickjacking",
        "severity": "HIGH",
        "recommended_value": "SAMEORIGIN",
        "cve_risk": "Clickjacking attacks",
    },
    "x-content-type-options": {
        "description": "X-Content-Type-Options — prevents MIME sniffing",
        "severity": "MEDIUM",
        "recommended_value": "nosniff",
        "cve_risk": "MIME confusion attacks",
    },
    "x-xss-protection": {
        "description": "X-XSS-Protection — browser XSS filter",
        "severity": "MEDIUM",
        "recommended_value": "1; mode=block",
        "cve_risk": "Reflected XSS attacks",
    },
    "referrer-policy": {
        "description": "Referrer-Policy — controls referrer information",
        "severity": "MEDIUM",
        "recommended_value": "strict-origin-when-cross-origin",
        "cve_risk": "Information leakage via referrer header",
    },
    "permissions-policy": {
        "description": "Permissions-Policy — restricts browser feature access",
        "severity": "LOW",
        "recommended_value": "geolocation=(), microphone=(), camera=()",
        "cve_risk": "Unauthorized access to device features",
    },
    "cross-origin-resource-policy": {
        "description": "CORP — restricts cross-origin resource reads",
        "severity": "LOW",
        "recommended_value": "same-origin",
        "cve_risk": "Cross-origin data leaks (Spectre)",
    },
    "cross-origin-opener-policy": {
        "description": "COOP — isolates browsing context",
        "severity": "LOW",
        "recommended_value": "same-origin",
        "cve_risk": "Cross-origin attacks via window.opener",
    },
    "cross-origin-embedder-policy": {
        "description": "COEP — requires CORP for all resources",
        "severity": "LOW",
        "recommended_value": "require-corp",
        "cve_risk": "Side-channel attacks (Spectre/Meltdown)",
    },
    "cache-control": {
        "description": "Cache-Control — prevents sensitive data caching",
        "severity": "MEDIUM",
        "recommended_value": "no-store, no-cache, must-revalidate",
        "cve_risk": "Sensitive data exposure via browser cache",
    },
    "clear-site-data": {
        "description": "Clear-Site-Data — clears browser data on logout",
        "severity": "LOW",
        "recommended_value": '"cache", "cookies", "storage"',
        "cve_risk": "Session persistence after logout",
    },
}

# ---------------------------------------------------------------------------
# Dangerous response headers (information disclosure)
# ---------------------------------------------------------------------------

DANGEROUS_HEADERS: Dict[str, str] = {
    "server": "Reveals server software and version",
    "x-powered-by": "Reveals backend technology",
    "x-aspnet-version": "Reveals ASP.NET version",
    "x-aspnetmvc-version": "Reveals ASP.NET MVC version",
    "x-generator": "Reveals CMS/framework",
    "x-drupal-cache": "Reveals Drupal CMS",
    "x-varnish": "Reveals Varnish cache",
    "via": "Reveals proxy/cache infrastructure",
}


# ---------------------------------------------------------------------------
# Core detection functions
# ---------------------------------------------------------------------------


def detect_waf(result: AuditResult) -> Optional[str]:
    """Detect WAF from response headers, cookies, body, and status."""
    headers_lower = {k.lower(): v.lower() for k, v in result.headers.items()}
    body = result.body_snippet.lower()
    cookies = headers_lower.get("set-cookie", "")
    detected: List[str] = []

    for waf_name, det_type, target, pattern in WAF_SIGNATURES:
        try:
            matched = False
            if det_type == "header":
                value = headers_lower.get(target, "")
                if value and re.search(pattern, value, re.IGNORECASE):
                    matched = True
            elif det_type == "cookie":
                if cookies and re.search(target, cookies, re.IGNORECASE):
                    if re.search(pattern, cookies, re.IGNORECASE):
                        matched = True
            elif det_type == "body":
                if body and re.search(target, body, re.IGNORECASE):
                    matched = True
            if matched and waf_name not in detected:
                detected.append(waf_name)
        except re.error:
            continue

    if detected:
        return detected[0]

    # Heuristic: small 403/406 with block keywords
    if result.status_code in (403, 406) and 0 < result.content_length < 2000 and body:
        block_words = ["blocked", "denied", "rejected", "firewall", "waf", "security", "attack", "malicious"]
        if any(w in body for w in block_words):
            return "Unknown WAF (heuristic)"

    return None


def detect_tech_stack(result: AuditResult) -> List[str]:
    """Detect technology stack from headers and body."""
    headers_lower = {k.lower(): v for k, v in result.headers.items()}
    body = result.body_snippet.lower()
    detected: List[str] = []

    for tech_name, match_spec, pattern in TECH_SIGNATURES:
        try:
            if match_spec.startswith("header:"):
                header_key = match_spec[7:]
                value = headers_lower.get(header_key, "")
                if value and re.search(pattern, value, re.IGNORECASE):
                    if tech_name not in detected:
                        detected.append(tech_name)
            elif match_spec == "body":
                if body and re.search(pattern, body, re.IGNORECASE):
                    if tech_name not in detected:
                        detected.append(tech_name)
        except re.error:
            continue

    return detected


def detect_information_disclosure(result: AuditResult) -> Dict[str, str]:
    """Detect headers that reveal sensitive server information."""
    headers_lower = {k.lower(): v for k, v in result.headers.items()}
    disclosed: Dict[str, str] = {}

    for header, risk in DANGEROUS_HEADERS.items():
        value = headers_lower.get(header)
        if value:
            disclosed[header] = f"Value: '{value}' — {risk}"

    return disclosed


def analyze_security_headers(result: AuditResult) -> Dict[str, Any]:
    """Analyze HTTP security headers against OWASP + extended recommendations."""
    headers_lower = {k.lower(): v for k, v in result.headers.items()}
    analysis: Dict[str, Any] = {}

    for header_name, info in SECURITY_HEADERS_REQUIRED.items():
        value = headers_lower.get(header_name)
        analysis[header_name] = {
            "status": "present" if value else "missing",
            "value": value,
            "description": info["description"],
            "severity": info["severity"],
            "recommended": info["recommended_value"],
            "cve_risk": info.get("cve_risk", ""),
        }

    return analysis


def compute_security_header_score(analysis: Dict[str, Any]) -> int:
    """Compute weighted security header score (0-100)."""
    weights = {"HIGH": 3, "MEDIUM": 2, "LOW": 1}
    total_weight = 0
    earned_weight = 0

    for header_data in analysis.values():
        w = weights.get(header_data["severity"], 1)
        total_weight += w
        if header_data["status"] == "present":
            earned_weight += w

    if total_weight == 0:
        return 0
    return int((earned_weight / total_weight) * 100)


def get_security_grade(score: int) -> str:
    """Convert score to letter grade."""
    if score >= 90:
        return "A+"
    elif score >= 80:
        return "A"
    elif score >= 70:
        return "B"
    elif score >= 60:
        return "C"
    elif score >= 50:
        return "D"
    else:
        return "F"
